title: "Centrum Treningowe"
description: "Aplikacja mobilna Centrum Treningowe"
url: "https://devinczi.github.io"
baseurl: ""
theme: minima

markdown: kramdown
kramdown:
  input: GFM

nav:
  - title: "Polityka Prywatno≈õci"
    url: "/"

plugins:
  - jekyll-feed
